version: '3'

services:

  db:
    image: postgres:16
    restart: always
    env_file:
      - "./postgres.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - "./postgres.env"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: sh -c "npm run dev"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  pgdata: